### PR TITLE
use default splash

### PR DESCRIPTION
**Pull request by Geokureli**
Requires HF 5.6 or greater

Switched to the standard HF splash with a few modifications. Since the old one looks a little jank IMO
Screenshot 2024-02-13 at 9 56 29 AM

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
this splash screen was actually a bit of an homage to the original flixel splash screen used in the flash version of canabalt! 
https://www.kongregate.com/games/adamatomic/canabalt

**Comment by Geokureli** [comment]
sure, can probably fix it by tweening to black rather than alphaless-white

**Comment by Geokureli** [comment]
Old version
https://github.com/ninjamuffin99/canabalt-hf/assets/2609513/c0293f72-4b32-401e-a3cb-314c5b8b5866

New Version
https://github.com/ninjamuffin99/canabalt-hf/assets/2609513/04d50048-d2b2-469c-bde4-f57852d2456b

**Review by ninjamuffin99 — APPROVED** [review]

**Comment by ninjamuffin99** [comment]
yay george :)

**Pull request merged**
